version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - node-network
    depends_on:
      - nodejs
  nodejs:
    build: .
    restart: always
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules      
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=fullcycle
    
    entrypoint: dockerize -wait tcp://db:3306 -timeout 200s docker-entrypoint.sh
    command: ["node", "index.js"]
    networks:
      - node-network
    depends_on:    
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - node-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=fullcycle

networks:
  node-network:
    driver: bridge
