version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - node-network
    depends_on:
      - nodejs
  nodejs:
    image: node:latest
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    expose:
      - "3000"
    command: ["node", "index.js"]
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    networks:
      - node-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle

networks:
  node-network:
    driver: bridge

